In [90]:
import numpy as np
import sklearn as sk

In [91]:
a = np.linspace(1, 50, 50)
a = a.reshape(-1,5)
rightmat = np.dot(a.T, a)
uu,vv = np.linalg.eig(rightmat)
#print('vv:', vv)
u,s,vt = np.linalg.svd(a)
print('vt:',vt.T)
print(vt)
#print(s)
sig = np.diag(s)
sig = np.vstack((sig, np.zeros((5,5))))
#print(sig)
q = np.dot(u,sig)
q = np.dot(q, vt)
#print(q)
print('#以上通过 q = s * sig * vT 恢复 v:右奇异矩阵的特征向量')

#print(u)
sig = np.diag(s[:2])
zipu = u[:, :2]
zipv = vt[:2, :]
zipq = np.dot(zipu,sig)
zipq = np.dot(zipq, zipv)
print(zipq)

vt: [[-0.42019675 -0.6507186   0.29396023 -0.17326432 -0.53250996]
 [-0.43350701 -0.33477108  0.16342582  0.07441585  0.81716233]
 [-0.44681727 -0.01882355 -0.63666966  0.60408511 -0.17243237]
 [-0.46012753  0.29712397 -0.39277908 -0.73836049  0.02341758]
 [-0.4734378   0.61307149  0.57206269  0.23312385 -0.13563758]]
[[-0.42019675 -0.43350701 -0.44681727 -0.46012753 -0.4734378 ]
 [-0.6507186  -0.33477108 -0.01882355  0.29712397  0.61307149]
 [ 0.29396023  0.16342582 -0.63666966 -0.39277908  0.57206269]
 [-0.17326432  0.07441585  0.60408511 -0.73836049  0.23312385]
 [-0.53250996  0.81716233 -0.17243237  0.02341758 -0.13563758]]
#以上通过 q = s * sig * vT 恢复 v:右奇异矩阵的特征向量
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]
 [26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35.]
 [36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45.]
 [46. 47. 48. 49. 50.]]
